name: Supercheck Core (Reusable)

on:
  workflow_call:
    inputs:
      auto_apply:
        description: "Apply safe fixes autonomously"
        required: false
        type: string
        default: "false"
      auto_commit:
        description: "Commit fixes directly to main (else PR)"
        required: false
        type: string
        default: "false"
      api_base:
        description: "Optional API base for runtime diag"
        required: false
        type: string
        default: ""
      queue_key:
        required: false
        type: string
        default: "queue:runs"
      timeout_sec:
        required: false
        type: string
        default: "75"
      poll_sec:
        required: false
        type: string
        default: "3"

permissions:
  contents: write
  pull-requests: write
  checks: write
  security-events: write

jobs:
  supercheck-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      # --- YAML correction (composite action in this repo) ---
      - name: YAML Corrector
        uses: StegVerse/StegVerse-Healer/.github/actions/yaml-corrector@main

      # --- Optional: run local scripts if present ---
      - name: Repo Inventory & Drift (if scripts exist)
        run: |
          set -e
          mkdir -p self_healing_out
          [ -f scripts/repo_audit.py ] && python3 scripts/repo_audit.py || echo "repo_audit.py missing"
          [ -f scripts/topic_drift_audit.py ] && python3 scripts/topic_drift_audit.py || echo "topic_drift_audit.py missing"
          [ -f scripts/collect_self_healing.py ] && python3 scripts/collect_self_healing.py || echo "collect_self_healing.py missing"

      - name: Auto-Triage (plan + optional apply)
        env:
          APPLY: ${{ inputs.auto_apply }}
        run: |
          if [ -f scripts/auto_triage.py ]; then
            if [ "${APPLY}" = "true" ]; then APPLY=1 python3 scripts/auto_triage.py; else python3 scripts/auto_triage.py; fi
          else
            echo "auto_triage.py missing"
          fi

      - name: Commit or PR changes
        if: ${{ inputs.auto_apply == 'true' }}
        env:
          DO_COMMIT: ${{ inputs.auto_commit }}
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          git config user.name "healer-bot"
          git config user.email "bot@stegverse.local"
          if [ "$DO_COMMIT" = "true" ]; then
            git add -A
            git commit -m "healer(auto): yaml normalize + triage" || echo "No changes"
            git push origin HEAD:main || true
          else
            BR="healer/supercheck-core-${GITHUB_RUN_ID}"
            git checkout -b "$BR"
            git add -A
            git commit -m "healer(auto): yaml normalize + triage" || echo "No changes"
            git push origin "$BR" || true
            TITLE="Healer: supercheck-core (auto)"
            BODY="Reusable workflow applied YAML normalization + triage. Review artifacts."
            curl -sS -X POST \
              -H "Authorization: Bearer ${GH_TOKEN}" \
              -H "Accept: application/vnd.github+json" \
              -d "$(jq -nc --arg t "$TITLE" --arg b "$BODY" --arg head "$BR" '{"title":$t,"body":$b,"head":$head,"base":"main"}')" \
              "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls" >/dev/null || true

      - name: Upload bundle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: healer_supercheck_core_bundle
          path: |
            self_healing_out/**
          if-no-files-found: warn
